### ISSUE TITLE
Script DDL - Atualização do schema - chaves únicas

### ISSUE THREAD

**Issue by HyQueC** [LucasPicazio/Proj-Integ-SI#15]
Atualização das definições de constraints para impedimento de inserção de registros potencialmente duplicados.

Exemplo na tabela de Membros:
Username e Password são uma dupla que nunca deve repetir.

**Comment by lTakezo** [comment]
Solução encontrada:
  - Adicionar constraint no banco de dados para "username" ser valor unico
